name: optoview_flutter
description: A neuro-optometry app built with Flutter.
publish_to: 'none'

# Versión de la app:
# 1.0.0 → versión visible
# +1    → número de compilación
version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  package_info_plus: ^8.3.1
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/smile.png
    - assets/images/logo.png
    - assets/images/test_peripheral.png
    - assets/images/location_peripheal.png
